// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANoDy4ZOJpmUFk4wERV9G2eNzlXN9DT0Q',
    appId: '1:894218036046:web:d5d670d3a51c02f8c1b41f',
    messagingSenderId: '894218036046',
    projectId: 'todoc10-maadi',
    authDomain: 'todoc10-maadi.firebaseapp.com',
    storageBucket: 'todoc10-maadi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2262n6NDo5R3weiXptKIOemiQS9FCWn4',
    appId: '1:894218036046:android:57e71d5ee32915fac1b41f',
    messagingSenderId: '894218036046',
    projectId: 'todoc10-maadi',
    storageBucket: 'todoc10-maadi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6jt0mFS9dUfjpaecCp7B7xDacr2qV68',
    appId: '1:894218036046:ios:08f4b237e25e4e46c1b41f',
    messagingSenderId: '894218036046',
    projectId: 'todoc10-maadi',
    storageBucket: 'todoc10-maadi.appspot.com',
    iosBundleId: 'com.example.todoC10Maadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6jt0mFS9dUfjpaecCp7B7xDacr2qV68',
    appId: '1:894218036046:ios:4d96582085f3b48bc1b41f',
    messagingSenderId: '894218036046',
    projectId: 'todoc10-maadi',
    storageBucket: 'todoc10-maadi.appspot.com',
    iosBundleId: 'com.example.todoC10Maadi.RunnerTests',
  );
}
